name: Build NixOS images
on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - arch: x86_64
            runner: ubuntu-latest
          - arch: aarch64
            runner: ubuntu-24.04-arm
    runs-on: ${{ matrix.runner }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@ef8a148080ab6020fd15196c2084a2eea5ff2d25 # v22
      - name: Build ISO
        env:
          NIX_PATH: nixpkgs=https://github.com/NixOS/nixpkgs/archive/74e2faf5965a12e8fa5cff799b1b19c6cd26b0e3.tar.gz
        run: |
          nix-shell -p nixos-generators --run \
            "nixos-generate --format iso --configuration ./myimage.nix -o result"
      - name: Upload
        uses: actions/upload-artifact@v7
        with:
          name: nixos-iso-${{ matrix.arch }}
          path: result/iso/*.iso
          if-no-files-found: error
